name: test-environment
channels:
  - defaults
dependencies:
  - notebook
  - numpy
  - pandas
  - dash
  - brotli
  - dash-html-components
  - dash-core-components
  - plotly
  - gunicorn
  - pip-chill
  - python=3.9
